### ISSUE TITLE
How to access docker-registry of magicleap ?

### ISSUE THREAD

**Issue by whale-hyper** [magicleap/arcloud#1]
I purchased magic leap2. 
And i'm going to install arcloud on local server.

But I have a problem that pull minio image from docker-registry of magicleap (registry.magicleap.io/enterprise).

Below is Error message 
```
44m         Normal    Pulling            pod/minio-0         Pulling image "quay.io/magicleap/scuttle:1.0.0"
44m         Warning   Failed             pod/minio-0         Failed to pull image "quay.io/magicleap/scuttle:1.0.0": 
                                                                                   rpc error: code = Unknown 
                                                                                   desc = failed to pull and unpack image "quay.io/magicleap/scuttle:1.0.0": 
                                                                                   failed to resolve reference "quay.io/magicleap/scuttle:1.0.0": 
                                                                                   pulling from host quay,io failed with status code [manifests 1.0.0]: 401 Unauthorized
44m         Warning   Failed             pod/minio-0         Error: ErrImagePull
```

How to access docker-registry of magicleap ?

**Comment by grozdanov** [comment]
Hi @whale-hyper! Would you please share which image the bundle is trying to pull from `registry.magicleap.io/enterprise` ?

**Comment by mterpstra** [comment]
Hello @whale-hyper.  You need to contact customer care to obtain credentials to access the registry.

**Comment by whale-hyper** [comment]
Hi Nikolay Grozdanov.

I tried to pull from "quay.io/magicleap"

And i solved this issue.
I got a docker registry secret from magicleap care.

Thank you.
Whale

2023년 1월 14일 (토) 오후 11:39, Nikolay Grozdanov ***@***.***>님이
작성:

**Comment by whale-hyper** [comment]
Hi Mark Terstra.

I solved this issue.
I got a docker registry secret from magicleap care.

Thank you.
Whale

2023년 1월 15일 (일) 오전 5:07, Mark Terpstra ***@***.***>님이 작성:
