### ISSUE TITLE
Cannot access env.example.

### ISSUE THREAD

**Issue by tokufxug** [magicleap/arcloud#2]
There is a link to env.sample in the setup instructions, but when I access it, it is Not Found.
https://github.com/magicleap/arcloud#environment-settings
https://github.com/magicleap/arcloud/blob/main/env.example

**Comment by grozdanov** [comment]
@tokufxug thank you for pointing the broken link out. I have updated the internal links from `README.md` file:
- env.example: https://github.com/magicleap/arcloud/blob/main/setup/env.example
