### ISSUE TITLE
Installation of mapping fails

### ISSUE THREAD

**Issue by Sythelux** [magicleap/arcloud#21]
I'm following the [Tutorial](https://developer-docs.magicleap.cloud/docs/guides/arcloud/arcloud-deployment-ova/) on how to setup the OVA image with virtualbox and upon doing the part with `./set_ip.sh --accept-sla 192.168.x.x` it checks and installs a couple of services, but when it reaches `mapping` it throws an Error and stops.

The last relevant lines are as follows:
```
2024/01/23 11:51:39 OK - identity-backend v1.22.6
Release "mapping" does not exist. Installing it now.
Error: release mapping failed, and has been uninstalled due to atomic being set: context deadline exceeded
```

I suppose it is useless to increase the timeout time for the helm command as suggested on the Internet, as it is already trying to execute for really long. I will still try this and also try to fully setup the VM again, but I'd like to know if there is something else I can try?

**Comment by gsagula** [comment]
@Sythelux What's your [runtime environment](https://developer-docs.magicleap.cloud/docs/guides/arcloud/arcloud-deployment-ova/#runtime-environments)?

**Comment by mterpstra** [comment]
@Sythelux A couple of questions for clarification:

1. Please confirm your runtime environment as @gsagula mentioned above.
2. What version of AR Cloud are you trying to install?  1.39.29 is the latest.
3. When supplying the IP address, please confirm you are putting your actual IP address and not 192.168.x.x (X.X part).

It may not be useless to try to increase the timeout.  The images inside the OVA are large and can take significant time to decompress depending on your machine and its resources.  I would recommend you increase it and try the installation steps again.

Please let us know how it goes and the confirmation to the questions above.

**Comment by Sythelux** [comment]
1. It is locally installed Windows - Virtualbox
2. I'm using the latest 1.39.29 ova downloaded from within the developer portal.
3. the 192.168.x.x is a local class C private address. I wanted to indicate that the container is running in LAN only for testing purposes. The Host is on 192.168.1.10 and the Container is connected to the host network and has 192.168.1.11

I will try the suggested ideas (might take until 29.1.24 as I have other projects to take care of, but will tell you if it worked)

**Comment by mterpstra** [comment]
@Sythelux just checking in to see if increasing the timeout solved the problem for you.  If not, here are two more things you can double check.

First, make sure hardware-assisted virtualization is enabled for the host machine's CPU.  Help on that is [here](https://developer-docs.magicleap.cloud/docs/guides/arcloud/arcloud-deployment-ova/#virtualization-support).

Second, make sure your system meets the minimum requirements [here](https://developer-docs.magicleap.cloud/docs/guides/arcloud/arcloud-deployment-ova/#resources).

Let us know if this helps.

**Comment by mterpstra** [comment]
Thank you for the feedback @Sythelux.
