### ISSUE TITLE
unable to reach svc via NLB on GKE 

### ISSUE THREAD

**Issue by nia-potato** [magicleap/arcloud#22]
hi after deployment via the [tutorial](https://developer-docs.magicleap.cloud/docs/guides/arcloud/arcloud-deployment-gcp/#install-arcloud) and running 

```
./setup.sh \
    --set global.domain=${DOMAIN} \
    --no-observability \
    --accept-sla \
    --debug
```
on GKE 

everything says it is up, but was unable to hit the domain via the setup script that provisioned the network load balancer, i was able to port forward and verify that the svc/minio was up and assuming the dahsboards are working, but was unable to reach from the domain and the ip. 

I can verify that the domain ip are binded prior to running the setup script. and the env variables populated. 

Thus i would like to confirm do i need to do any additional NLB -> svc routing since i dont see a ingress or a backend config, it seems like the flow is just NLB -> svc after the setup scripts completes.

**Comment by mterpstra** [comment]
Met with @nia-potato and found an issue in the firewall.  Fixed the issue and the cluster is not accessible.  One final change was discussed and when that change is made and confirmed, we will close this out.

**Comment by mterpstra** [comment]
Fixed per above.
