### ISSUE TITLE
AR Cloud 1.7.84 Release Notes

### ISSUE THREAD

**Issue by tokufxug** [magicleap/arcloud#3]
What upgrades were made to AR Cloud 1.7.84? Is Magic Leap 2 OS 1.1.0 supported? 
By the way, I heard that AR Cloud 1.0.2 supports Magic Leap 2 OS 1.1.0-dev1 but not 1.1.0-dev2.

**Comment by mterpstra** [comment]
@tokufxug 

AR Cloud 1.7.84 contains the following:
- Various bug fixes for localization and mapping
- Support for AWS
- Map Merge (the ability to merge two maps in a single space to one map).
- Dashboard Events

Regarding AR Cloud 1.0.2, we recommend you update both AR Cloud and your OS to the latest versions.  They both include bug fixes that you will want even if you don't use the new features.

**Comment by tokufxug** [comment]
@mterpstra 
>Regarding AR Cloud 1.0.2, we recommend you update both AR Cloud and your OS to the latest versions. They both include bug fixes that you will want even if you don't use the new features.

Are you talking about AR Cloud 1.0.2?
Some information is also available, such as the following, which uses one previous version.
<img width="724" alt="スクリーンショット 2023-01-19 11 32 20" src="https://user-images.githubusercontent.com/323081/213342136-f6fb8464-3563-45d0-8c69-351fb3fffe32.png">
Please clarify which version of Magic Leap 2 OS supports AR Cloud 1.7.84.

**Comment by mterpstra** [comment]
@tokufxug You are correct, do not use 1.1.0-dev2 with AR Cloud.  If you want to use AR Cloud, please use 1.1.0 (secure) with AR Cloud 1.7.84.  In The Hubs Package Manager, the OS version you should use is labeled **Magic Leap OS - Jan 2023 - B3E.221128.08-R.092 (Secure Device Only)**
