### ISSUE TITLE
For information on setting environment variables

### ISSUE THREAD

**Issue by tokufxug** [magicleap/arcloud#4]
I am currently implementing an AR Cloud setup using GCP. I am not sure what information should be set when setting the environment variables at the beginning.

https://github.com/magicleap/arcloud/#environment-settings
https://github.com/magicleap/arcloud/#infrastructure-on-gcp

Perhaps there is a process that should be set up for the information to be set in the environment variables, but I can't read it from the documentation. I would appreciate an answer to the above.

**Comment by grozdanov** [comment]
Hi @tokufxug!
Please see the content of [env.example](https://github.com/magicleap/arcloud/blob/main/setup/env.example) and let us know if that resolves your question.

**Comment by mterpstra** [comment]
@tokufxug Did the reply above resolve your question regarding the environment variables?

**Comment by tokufxug** [comment]
@grozdanov @mterpstra I think this information depends on the environment, such as REGISTRY_USERNAME and REGISTRY_PASSWORD, but I have no idea because there is no information on the construction of that environment. This Issue has not been resolved.

**Comment by mterpstra** [comment]
@tokufxug It may help if you can tell us what you are stuck on specifically.  Are you receiving an error message during installation or are you still setting up your supporting infrastructure? 

REGISTRY_USERNAME and REGISTRY_PASSWORD are not cloud specific values.  These are the values obtained via customer care and are used to pull and install AR Cloud images while the setup script is running.

**Comment by tokufxug** [comment]
@mterpstra 

>REGISTRY_USERNAME and REGISTRY_PASSWORD are not cloud specific values. These are the values obtained via customer care and are used to pull and install AR Cloud images while the setup script is running.

This is the first time I have heard of setting up the information given by the customer center. Where was that information stated?

Is it possible to build an environment without this kind of information? Besides this information, is there any other information that is missing when building?

**Comment by mterpstra** [comment]
@tokufxug These values are provider per customer and are given at the time of purchase.  These values are currently required to install AR Cloud and no other information is needed.
